public DataSourceElementBeanInfo() {
    super(DataSourceElement.class);
    createPropertyGroup("varName", new String[] { "dataSource" });
    createPropertyGroup("pool", new String[] { "poolMax", "timeout", "trimInterval", "autocommit", "transactionIsolation", "poolPreparedStatements", "preinit", "initQuery" });
    createPropertyGroup("keep-alive", new String[] { "keepAlive", "connectionAge", "checkQuery" });
    createPropertyGroup("database", new String[] { "dbUrl", "driver", "username", "password", "connectionProperties" });
    PropertyDescriptor p = property("dataSource");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "");
    p = property("poolMax");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "0");
    p = property("timeout");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "10000");
    p = property("trimInterval");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "60000");
    p = property("autocommit");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, Boolean.TRUE);
    p = property("transactionIsolation");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "DEFAULT");
    p.setValue(NOT_EXPRESSION, Boolean.TRUE);
    Set<String> modesSet = TRANSACTION_ISOLATION_MAP.keySet();
    String[] modes = modesSet.toArray(new String[modesSet.size()]);
    p.setValue(TAGS, modes);
    p = property("poolPreparedStatements");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT_NOT_SAVED, Boolean.TRUE);
    p.setValue(DEFAULT, "-1");
    p = property("preinit");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, Boolean.FALSE);
    p = property("initQuery", TypeEditor.TextAreaEditor);
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "");
    p = property("keepAlive");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, Boolean.TRUE);
    p = property("connectionAge");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "5000");
    p = property("checkQuery", TypeEditor.ComboStringEditor);
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "");
    p.setValue(TAGS, getListCheckQuery());
    p = property("dbUrl");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "");
    p = property("driver", TypeEditor.ComboStringEditor);
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "");
    p.setValue(TAGS, getListJDBCDriverClass());
    p = property("username");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "");
    p = property("password", TypeEditor.PasswordEditor);
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "");
    p = property("connectionProperties");
    p.setValue(NOT_UNDEFINED, Boolean.TRUE);
    p.setValue(DEFAULT, "");
}